import fs from 'node:fs';import assert from 'node:assert/strict';
const g=fs.readFileSync('./game.js','utf8'),api=fs.readFileSync('./api/asset.js','utf8'),sw=fs.readFileSync('./sw.js','utf8');
assert(g.includes("assets/32699/v1/model.glb")||api.includes("assets/32699/v1/model.glb"),'stable survivor asset');
assert(!g.includes('normalizeCharacterModel'),'old runtime normalization removed');
assert(g.includes('prepareCharacterModel'),'safe character preparation');
assert(g.includes('moveColliders=candidates.filter'),'conservative colliders');
assert(g.includes('collisionGrace=1.25'),'movement recovery');
assert(g.includes('spawnOpeningWave'),'opening visible wave');
assert(g.includes('cameraColliders=[]'),'broad camera boxes disabled');
assert(g.includes("new THREE.AnimationMixer(s.model)"),'survivor mixer attached to model');
assert(g.includes("new THREE.AnimationMixer(t.model)"),'infected mixer attached to model');
assert(sw.includes('v5-5-recovery'),'fresh service worker cache');
console.log('PASS stable metre-scale survivor asset');
console.log('PASS destructive runtime actor recentering removed');
console.log('PASS conservative gameplay colliders');
console.log('PASS automatic movement collision recovery');
console.log('PASS opening enemies spawn in front of player');
console.log('PASS broad camera AABB collision disabled');
console.log('PASS actor animation mixers bind to imported models');
console.log('PASS service-worker cache revved');
console.log('8/8 V5.5 regression checks passed');
